// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


function join(strings, separator) {
  if (strings) {
    var xs = strings[1];
    var x = strings[0];
    if (xs) {
      return x + (separator + join(xs, separator));
    } else {
      return x;
    }
  } else {
    return "";
  }
}

function range(a, b) {
  var match = +(a > b);
  if (match !== 0) {
    return /* [] */0;
  } else {
    return /* :: */[
            a,
            range(a + 1 | 0, b)
          ];
  }
}

exports.join = join;
exports.range = range;
/* No side effect */
