// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Util$ReactTemplate = require("../src/util.bs.js");

describe("range()", (function () {
        Jest.test("0..5", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            0,
                            /* :: */[
                              1,
                              /* :: */[
                                2,
                                /* :: */[
                                  3,
                                  /* :: */[
                                    4,
                                    /* :: */[
                                      5,
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ], Jest.Expect[/* expect */0](Util$ReactTemplate.range(0, 5)));
              }));
        Jest.test("10..10", (function () {
                return Jest.Expect[/* toEqual */12](/* :: */[
                            10,
                            /* [] */0
                          ], Jest.Expect[/* expect */0](Util$ReactTemplate.range(10, 10)));
              }));
        return Jest.test("100..1", (function () {
                      return Jest.Expect[/* toEqual */12](/* [] */0, Jest.Expect[/* expect */0](Util$ReactTemplate.range(100, 1)));
                    }));
      }));

describe("join()", (function () {
        Jest.test("with non-empty separator", (function () {
                return Jest.Expect[/* toBe */2]("this,that", Jest.Expect[/* expect */0](Util$ReactTemplate.join(/* :: */[
                                    "this",
                                    /* :: */[
                                      "that",
                                      /* [] */0
                                    ]
                                  ], ",")));
              }));
        return Jest.test("with empty separator", (function () {
                      return Jest.Expect[/* toBe */2]("foobar", Jest.Expect[/* expect */0](Util$ReactTemplate.join(/* :: */[
                                          "foo",
                                          /* :: */[
                                            "bar",
                                            /* [] */0
                                          ]
                                        ], "")));
                    }));
      }));

/*  Not a pure module */
